spring:
  application:
    name: jiyun-service-order
  nacos:
    discovery:
      server-addr: 127.0.0.1:8848
    loadbalancer:
      nacos:
        enabled: true # 手动开启nacos负载均衡,即便是引入了Nacos的依赖，但因为默认是使用的轮训，所以不生效。

server:
  port: 9003

#eureka:
#  client:
#    serviceUrl: # eureka server的路径
#      defaultZone: http://localhost:8000/eureka/
#  instance:
#    #使用ip注册，否则会使用主机名注册了（此处考虑到对老版本的兼容，新版本经过实验都是ip）
#    prefer-ip-address: true
#    #自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
#    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@

feign:
  client:
    config:
      default:
        connect-timeout: 2000 # 建立连接需要的时间
        read-timeout: 5000   # 远程调用的响应时间

  compression:
    request:
      enabled: true # 请求开启压缩
      mime-types: text/xml, application/xml, application/json # 压缩格式,默认值
      min-request-size: 2048 # 设置触发压缩的大小下限，此处也是默认值
    response:
      enabled: true # 开启响应压缩
