server:
  port: 9008

eureka:
  client:
    serviceUrl: # eureka server的路径
      defaultZone: http://localhost:8000/eureka/
  instance:
    #使用ip注册，否则会使用主机名注册了（此处考虑到对老版本的兼容，新版本经过实验都是ip）
    prefer-ip-address: true
    #自定义实例显示格式，加上版本号，便于多版本管理，注意是ip-address，早期版本是ipAddress
    instance-id: ${spring.cloud.client.ip-address}:${spring.application.name}:${server.port}:@project.version@

spring:
  application:
    name: sysgateway
  main:
    web-application-type: reactive
  cloud:
    gateway:
      #开启网关的跨域功能
      globalcors:
        cors-configurations:
          '[/**]': # 匹配所有请求
            allowedOrigins: "*" #跨域处理 允许所有的域
            allowedMethods: # 支持的方法
              - GET
              - POST
              - PUT
              - DELETE
      routes: #路由的配置，通常会为每个微服务配置一个路由信息，每个路由信息都有一个唯一的ID
        - id: goods #唯一标识
          uri: lb://jiyun-service-goods # 负载到商品服务
          predicates: # 什么样的请求可以访问上面的uri
            - Path=/goods/**  #所有URI以goods开头的请求
          filters:
            - StripPrefix= 1 # 截取第一个URI
        - id: order
          uri: lb://jiyun-service-order # 负载均衡到Order，如果注册中心注册了多个订单服务，轮询。
          predicates:
            - Path=/order/**
          filters:
            - StripPrefix= 1